// Passive items. Almost everything here is a pure stat modifier: the integrator
// folds `G.items.map(i => i.mods)` through computeStats every frame, so an item
// only needs code when it does something once, at the moment of purchase.
//
// Every key inside `mods` must exist in BASE_STATS (js/stats.js) — computeStats
// silently drops unknown keys, so a typo becomes an item that does nothing.

/**
 * Item def: { id, name, tier, price, mods, tags, desc, color }
 * Optional: `max` (how many copies may be owned, default 4), `minWave` (earliest
 * wave the item may be offered), `grant` (one-shot payout handled below).
 */
export const ITEM_DEFS = {
  /* ------------------------------------------------------------- tier 1 */

  rusty_nail: {
    id: "rusty_nail",
    name: "Rusty Nail",
    tier: 1,
    price: 10,
    mods: { meleeDamage: 6 },
    tags: ["melee"],
    color: "#b4693c",
    desc: "Tetanus is a small price for a sharper swing.",
  },
  lead_shot: {
    id: "lead_shot",
    name: "Bag of Lead Shot",
    tier: 1,
    price: 10,
    mods: { rangedDamage: 6, speed: -2 },
    tags: ["ranged"],
    color: "#8d94a6",
    desc: "Heavier rounds hit harder. Also, they are heavy.",
  },
  spare_battery: {
    id: "spare_battery",
    name: "Spare Battery",
    tier: 1,
    price: 12,
    mods: { attackSpeed: 6 },
    tags: ["speed"],
    color: "#e0c542",
    desc: "Everything cycles a little faster with juice to spare.",
  },
  lucky_tooth: {
    id: "lucky_tooth",
    name: "Lucky Tooth",
    tier: 1,
    price: 11,
    mods: { luck: 9 },
    tags: ["luck"],
    color: "#f2ead6",
    desc: "Not yours. That is why it still works.",
  },
  jogging_shoes: {
    id: "jogging_shoes",
    name: "Jogging Shoes",
    tier: 1,
    price: 10,
    mods: { speed: 7 },
    tags: ["speed", "dodge"],
    color: "#66c489",
    desc: "The arena is a track meet with teeth.",
  },
  clean_bandage: {
    id: "clean_bandage",
    name: "Clean Bandage",
    tier: 1,
    price: 9,
    mods: { maxHp: 3, hpRegen: 0.4 },
    tags: ["tank", "regen"],
    color: "#efe6dd",
    desc: "Slightly more of you, mending slightly faster.",
  },
  scrap_plating: {
    id: "scrap_plating",
    name: "Scrap Plating",
    tier: 1,
    price: 12,
    mods: { armor: 3, speed: -4 },
    tags: ["tank"],
    color: "#7f8794",
    desc: "Bolted-on car door. Stops teeth, ruins your sprint.",
  },
  whetstone: {
    id: "whetstone",
    name: "Whetstone",
    tier: 1,
    price: 13,
    mods: { meleeDamage: 10, attackSpeed: -4 },
    tags: ["melee"],
    color: "#a8a29b",
    desc: "A slower, meaner edge. Take your time with it.",
  },
  pocket_sand: {
    id: "pocket_sand",
    name: "Pocket Sand",
    tier: 1,
    price: 11,
    mods: { dodge: 5 },
    tags: ["dodge"],
    color: "#dcc189",
    desc: "Sha-sha! Hard to bite what you cannot see.",
  },
  copper_wire: {
    id: "copper_wire",
    name: "Copper Wire",
    tier: 1,
    price: 12,
    mods: { engineering: 10 },
    tags: ["engineering"],
    color: "#c97b3c",
    desc: "Your turrets appreciate the upgrade. They said so.",
  },
  gardening_gloves: {
    id: "gardening_gloves",
    name: "Gardening Gloves",
    tier: 1,
    price: 11,
    mods: { harvesting: 3 },
    tags: ["economy"],
    color: "#7fa25a",
    desc: "Scrape more out of the dirt between fights.",
  },
  cracked_lens: {
    id: "cracked_lens",
    name: "Cracked Lens",
    tier: 1,
    price: 13,
    mods: { critChance: 5 },
    tags: ["crit"],
    color: "#8fd4e8",
    desc: "You only need the one good spot in the glass.",
  },
  energy_drink: {
    id: "energy_drink",
    name: "Warm Energy Drink",
    tier: 1,
    price: 12,
    mods: { attackSpeed: 9, maxHp: -2 },
    tags: ["speed", "tradeoff"],
    color: "#c8e04a",
    desc: "Twitchy hands, bad heart. Worth it.",
  },
  thick_skull: {
    id: "thick_skull",
    name: "Thick Skull",
    tier: 1,
    price: 12,
    mods: { maxHp: 5, speed: -4 },
    tags: ["tank"],
    color: "#d9cfbb",
    desc: "Nothing important in there to protect, so it takes hits well.",
  },
  first_aid_kit: {
    id: "first_aid_kit",
    name: "First Aid Kit",
    tier: 1,
    price: 14,
    mods: { maxHp: 2 },
    tags: ["heal", "tank"],
    color: "#e35d5d",
    grant: { heal: 999 },
    desc: "Patches you up completely, right now, and leaves a little padding.",
  },
  found_wallet: {
    id: "found_wallet",
    name: "Found Wallet",
    tier: 1,
    price: 10,
    mods: { luck: 4, harvesting: 1 },
    tags: ["economy", "luck"],
    color: "#8a6a44",
    grant: { materials: 6 },
    desc: "Still has cash in it. Nobody is coming back for it.",
  },

  /* ------------------------------------------------------------- tier 2 */

  serrated_edge: {
    id: "serrated_edge",
    name: "Serrated Edge",
    tier: 2,
    price: 24,
    mods: { meleeDamage: 14, lifeSteal: 2 },
    tags: ["melee", "lifesteal"],
    color: "#c4483f",
    desc: "Ragged wounds bleed, and bleeding feeds you.",
  },
  marksman_scope: {
    id: "marksman_scope",
    name: "Marksman Scope",
    tier: 2,
    price: 26,
    mods: { rangedDamage: 12, range: 12, meleeDamage: -12 },
    tags: ["ranged", "tradeoff"],
    color: "#5aa9d6",
    desc: "You stop thinking about anything closer than forty feet.",
  },
  adrenaline_shot: {
    id: "adrenaline_shot",
    name: "Adrenaline Shot",
    tier: 2,
    price: 25,
    mods: { attackSpeed: 12, armor: -2 },
    tags: ["speed", "tradeoff"],
    color: "#e88f3c",
    desc: "You will not feel the hits until later. You will feel them later.",
  },
  hard_hat: {
    id: "hard_hat",
    name: "Hard Hat",
    tier: 2,
    price: 24,
    mods: { armor: 5, maxHp: 2 },
    tags: ["tank"],
    color: "#e6c229",
    desc: "Regulation safety equipment for an unregulated situation.",
  },
  ballet_slippers: {
    id: "ballet_slippers",
    name: "Ballet Slippers",
    tier: 2,
    price: 25,
    mods: { dodge: 8, speed: 5, maxHp: -3 },
    tags: ["dodge", "tradeoff"],
    color: "#e6a8c0",
    desc: "Grace instead of substance. Do not get touched.",
  },
  leech_ring: {
    id: "leech_ring",
    name: "Leech Ring",
    tier: 2,
    price: 27,
    mods: { lifeSteal: 5 },
    tags: ["lifesteal"],
    color: "#9b4f8e",
    desc: "It drinks first and shares what is left.",
  },
  blueprint: {
    id: "blueprint",
    name: "Smudged Blueprint",
    tier: 2,
    price: 26,
    mods: { engineering: 22 },
    tags: ["engineering"],
    color: "#4f7fc4",
    desc: "Half the lines are coffee. The turrets figure it out.",
  },
  prospectors_pick: {
    id: "prospectors_pick",
    name: "Prospector's Pick",
    tier: 2,
    price: 24,
    mods: { harvesting: 5, luck: 6 },
    tags: ["economy", "luck"],
    color: "#b08d57",
    desc: "There is money in this arena if you dig between corpses.",
  },
  hollow_points: {
    id: "hollow_points",
    name: "Hollow Points",
    tier: 2,
    price: 28,
    mods: { critChance: 9, maxHp: -3 },
    tags: ["crit", "ranged", "tradeoff"],
    color: "#d0d6de",
    desc: "Illegal in most arenas. This is not most arenas.",
  },
  metronome: {
    id: "metronome",
    name: "Metronome",
    tier: 2,
    price: 25,
    mods: { attackSpeed: 9, range: 9 },
    tags: ["speed", "elemental"],
    color: "#c9a227",
    desc: "Tick. Fire. Tick. Fire. The rhythm carries further than you think.",
  },
  protein_bar: {
    id: "protein_bar",
    name: "Chalky Protein Bar",
    tier: 2,
    price: 23,
    mods: { maxHp: 7, hpRegen: 0.8, speed: -3 },
    tags: ["tank", "regen"],
    color: "#a97e4f",
    desc: "Tastes like drywall. Builds you like drywall.",
  },
  gamblers_die: {
    id: "gamblers_die",
    name: "Gambler's Die",
    tier: 2,
    price: 26,
    mods: { luck: 18, armor: -3 },
    tags: ["luck", "tradeoff"],
    color: "#e0e0e0",
    desc: "Better offers, worse odds of surviving them.",
  },
  storm_capacitor: {
    id: "storm_capacitor",
    name: "Storm Capacitor",
    tier: 2,
    price: 29,
    mods: { damage: 9, attackSpeed: 5, maxHp: -3 },
    tags: ["elemental", "tradeoff"],
    color: "#7ad3f0",
    desc: "Holds a charge it very much wants to release.",
  },
  spiked_boots: {
    id: "spiked_boots",
    name: "Spiked Boots",
    tier: 2,
    price: 24,
    mods: { meleeDamage: 10, speed: 6, range: -8 },
    tags: ["melee", "speed"],
    color: "#6d7a5c",
    desc: "Closing distance is the whole plan.",
  },
  field_medkit: {
    id: "field_medkit",
    name: "Field Medkit",
    tier: 2,
    price: 27,
    mods: { hpRegen: 1.2, maxHp: 3 },
    tags: ["regen", "heal"],
    grant: { heal: 999 },
    color: "#e07070",
    desc: "Tops you off now and keeps stitching between waves.",
  },

  /* ------------------------------------------------------------- tier 3 */

  bloodthirsty_blade: {
    id: "bloodthirsty_blade",
    name: "Bloodthirsty Blade",
    tier: 3,
    price: 48,
    mods: { meleeDamage: 28, lifeSteal: 4, maxHp: -6 },
    tags: ["melee", "lifesteal", "tradeoff"],
    color: "#a32020",
    minWave: 4,
    desc: "It takes a little off the top of every owner. Swings gloriously.",
  },
  railgun_coil: {
    id: "railgun_coil",
    name: "Railgun Coil",
    tier: 3,
    price: 50,
    mods: { rangedDamage: 26, range: 10, attackSpeed: -10 },
    tags: ["ranged", "tradeoff"],
    color: "#5fc8e8",
    minWave: 4,
    desc: "Charges slow. Arrives instantly.",
  },
  vampiric_fang: {
    id: "vampiric_fang",
    name: "Vampiric Fang",
    tier: 3,
    price: 52,
    mods: { lifeSteal: 9, damage: 6, hpRegen: -1 },
    tags: ["lifesteal", "tradeoff"],
    color: "#8e3b6b",
    minWave: 5,
    desc: "You no longer heal on your own. You heal on theirs.",
  },
  tesla_core: {
    id: "tesla_core",
    name: "Tesla Core",
    tier: 3,
    price: 54,
    mods: { engineering: 32, damage: 10 },
    tags: ["engineering", "elemental"],
    color: "#7fe3ff",
    minWave: 5,
    desc: "The hum means the machines are happy. Stand clear anyway.",
  },
  phantom_cloak: {
    id: "phantom_cloak",
    name: "Phantom Cloak",
    tier: 3,
    price: 50,
    mods: { dodge: 13, speed: 9, armor: -4 },
    tags: ["dodge", "tradeoff"],
    color: "#6b6fa8",
    minWave: 4,
    desc: "When it does connect, it connects with all of you.",
  },
  iron_lung: {
    id: "iron_lung",
    name: "Iron Lung",
    tier: 3,
    price: 47,
    mods: { maxHp: 14, hpRegen: 1.5, speed: -8 },
    tags: ["tank", "regen"],
    color: "#94a3ad",
    minWave: 4,
    desc: "Breathes for you. Refuses to hurry.",
  },
  gilded_scythe: {
    id: "gilded_scythe",
    name: "Gilded Scythe",
    tier: 3,
    price: 46,
    mods: { harvesting: 10, luck: 22, damage: -6 },
    tags: ["economy", "luck", "tradeoff"],
    color: "#d4af37",
    minWave: 5,
    desc: "A reaper's tool, refitted for accounting.",
  },
  glass_cannon: {
    id: "glass_cannon",
    name: "Glass Cannon",
    tier: 3,
    price: 55,
    mods: { damage: 30, maxHp: -9, armor: -5 },
    tags: ["damage", "elemental", "tradeoff"],
    color: "#c6f0ff",
    minWave: 6,
    max: 2,
    desc: "Enormous output. Structurally, you are a window now.",
  },
  hair_trigger: {
    id: "hair_trigger",
    name: "Hair Trigger",
    tier: 3,
    price: 49,
    mods: { attackSpeed: 22, damage: -8 },
    tags: ["speed", "tradeoff"],
    color: "#e8b04a",
    minWave: 4,
    desc: "Quantity has a quality all its own.",
  },
  sniper_nest: {
    id: "sniper_nest",
    name: "Sniper's Nest",
    tier: 3,
    price: 51,
    mods: { range: 30, rangedDamage: 14, speed: -10 },
    tags: ["ranged", "tradeoff"],
    color: "#7c8f5a",
    minWave: 6,
    desc: "You have found your spot. Do not leave it.",
  },
  executioners_mark: {
    id: "executioners_mark",
    name: "Executioner's Mark",
    tier: 3,
    price: 53,
    mods: { critChance: 15, meleeDamage: 10, dodge: -5 },
    tags: ["crit", "melee", "tradeoff"],
    color: "#b03050",
    minWave: 6,
    desc: "You do not flinch, and you do not miss the soft parts.",
  },
  bulwark_shield: {
    id: "bulwark_shield",
    name: "Bulwark Shield",
    tier: 3,
    price: 48,
    mods: { armor: 8, maxHp: 6, attackSpeed: -8 },
    tags: ["tank", "tradeoff"],
    color: "#8b95a6",
    minWave: 5,
    desc: "One arm is permanently busy. The other one copes.",
  },

  /* ------------------------------------------------------------- tier 4 */

  berserker_heart: {
    id: "berserker_heart",
    name: "Berserker's Heart",
    tier: 4,
    price: 82,
    mods: { meleeDamage: 50, lifeSteal: 10, maxHp: -10, range: -25 },
    tags: ["melee", "lifesteal", "tradeoff"],
    color: "#8b1a1a",
    minWave: 8,
    max: 1,
    desc: "It only beats in the middle of the swarm. Get there.",
  },
  singularity_lens: {
    id: "singularity_lens",
    name: "Singularity Lens",
    tier: 4,
    price: 88,
    mods: { critChance: 28, damage: 12, attackSpeed: -14 },
    tags: ["crit", "elemental", "tradeoff"],
    color: "#b98cff",
    minWave: 9,
    max: 1,
    desc: "Every shot takes longer and means more.",
  },
  overclocked_core: {
    id: "overclocked_core",
    name: "Overclocked Core",
    tier: 4,
    price: 90,
    mods: { engineering: 65, damage: 14, maxHp: -8 },
    tags: ["engineering", "tradeoff"],
    color: "#4de0d0",
    minWave: 9,
    max: 1,
    desc: "The turrets are running hotter than the safety sheet allows.",
  },
  ghost_protocol: {
    id: "ghost_protocol",
    name: "Ghost Protocol",
    tier: 4,
    price: 85,
    mods: { dodge: 20, speed: 20, maxHp: -12 },
    tags: ["dodge", "speed", "tradeoff"],
    color: "#9fe8ff",
    minWave: 8,
    max: 1,
    desc: "Barely here at all. Which is the point, and the problem.",
  },
  titan_plating: {
    id: "titan_plating",
    name: "Titan Plating",
    tier: 4,
    price: 84,
    mods: { armor: 14, maxHp: 22, speed: -16, attackSpeed: -8 },
    tags: ["tank", "tradeoff"],
    color: "#6f7d8c",
    minWave: 8,
    max: 1,
    desc: "A walking bunker. Emphasis on walking, slowly.",
  },
  midas_tumor: {
    id: "midas_tumor",
    name: "Midas Tumor",
    tier: 4,
    price: 80,
    mods: { harvesting: 22, luck: 40, maxHp: -10 },
    tags: ["economy", "luck", "tradeoff"],
    color: "#f0c419",
    minWave: 8,
    max: 1,
    grant: { materials: 25 },
    desc: "Benign, mostly. Sheds coins when you are not looking.",
  },
  eye_of_the_storm: {
    id: "eye_of_the_storm",
    name: "Eye of the Storm",
    tier: 4,
    price: 89,
    mods: { rangedDamage: 42, range: 25, meleeDamage: -30 },
    tags: ["ranged", "tradeoff"],
    color: "#5ab7ff",
    minWave: 9,
    max: 1,
    desc: "Calm in the center, ruinous at the edges. Never let them close.",
  },
  philosophers_organ: {
    id: "philosophers_organ",
    name: "Philosopher's Organ",
    tier: 4,
    price: 86,
    mods: { hpRegen: 4, lifeSteal: 12, maxHp: 12, damage: -10 },
    tags: ["lifesteal", "regen", "tank", "tradeoff"],
    color: "#d6a3e8",
    minWave: 9,
    max: 1,
    grant: { heal: 999 },
    desc: "You will outlast anything. You will not out-hit it.",
  },
  perpetual_engine: {
    id: "perpetual_engine",
    name: "Perpetual Engine",
    tier: 4,
    price: 92,
    mods: { attackSpeed: 30, speed: 12, engineering: 20, maxHp: -8 },
    tags: ["speed", "engineering", "tradeoff"],
    color: "#ffd166",
    minWave: 10,
    max: 1,
    desc: "It has not stopped since they built it. Neither will you.",
  },
  war_crown: {
    id: "war_crown",
    name: "War Crown",
    tier: 4,
    price: 95,
    mods: { damage: 25, critChance: 10, dodge: -10, armor: -4 },
    tags: ["damage", "crit", "tradeoff"],
    color: "#e8d17a",
    minWave: 10,
    max: 1,
    desc: "Worn by champions, all of whom died wearing it.",
  },
};

const DEFAULT_MAX_COPIES = 4;

/** How many copies of `id` the player already owns. */
function ownedCount(G, id) {
  let n = 0;
  const items = G.items || [];
  for (let i = 0; i < items.length; i++) if (items[i].id === id) n++;
  return n;
}

/**
 * Items eligible to roll at `tier`. Filters out copies the player has maxed out
 * and build-defining items gated behind a minimum wave, so wave 1 never offers
 * a run-warping tier 4 relic even on a lucky roll.
 */
export function itemPool(G, tier) {
  const wave = G && G.wave ? G.wave : 1;
  const out = [];
  for (const id in ITEM_DEFS) {
    const def = ITEM_DEFS[id];
    if (def.tier !== tier) continue;
    if (def.minWave && wave < def.minWave) continue;
    if (ownedCount(G, id) >= (def.max || DEFAULT_MAX_COPIES)) continue;
    out.push(def);
  }
  return out;
}

/**
 * One-shot effects at pickup. Stat mods are handled by computeStats, so only
 * items carrying a `grant` block do anything here. The heal cap reads the stat
 * block from before this item was folded in; that is fine — the integrator
 * recomputes right after, and a full heal stays a full heal.
 */
export function applyItemEffects(G, item) {
  if (!item || !item.grant) return;
  const g = item.grant;
  if (g.materials && typeof G.grantMaterials === "function") G.grantMaterials(g.materials);
  if (g.xp && typeof G.grantXp === "function") G.grantXp(g.xp);
  if (g.heal && G.player) {
    const cap = G.stats ? G.stats.maxHp : G.player.hp + g.heal;
    G.player.hp = Math.min(cap, G.player.hp + g.heal);
  }
}
