const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id); let W,H,dpr,raf,last=0,keys={},mouse={x:0,y:0},state='menu',wave=1,score=0,level=1,xp=0,hp=100,shield=40,elapsed=0,spawned=0, kills=0, best=Number(localStorage.getItem('voidBest')||0),enemies=[],bullets=[],particles=[],pickups=[],player,shake=0;
const upgrades=[['ϟ','OVERCHARGE','+25% weapon damage'],['◇','PHASE SKIN','+20 max shield'],['⌁','RAPID CORE','+18% fire rate'],['✦','VOID HEART','Restore 30 hull']];
function resize(){dpr=devicePixelRatio||1;const r=canvas.getBoundingClientRect();W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function reset(){wave=1;score=0;level=1;xp=0;hp=100;shield=40;elapsed=0;spawned=0;kills=0;enemies=[];bullets=[];particles=[];pickups=[];player={x:W/2,y:H/2,r:12,angle:0,damage:12,rate:1,shoot:0,dash:0,inv:0,maxShield:40}; spawnWave();updateHud()}
function spawnWave(){const count=5+wave*3;spawned=count;for(let i=0;i<count;i++){let side=Math.floor(Math.random()*4),x=side%2?Math.random()*W:(side===0?-30:W+30),y=side%2?(side===1?-30:H+30):Math.random()*H;let type=Math.random()<Math.min(.18,wave*.025)?'brute':'drone';enemies.push({x,y,r:type==='brute'?17:10,type,hp:type==='brute'?42+wave*3:18+wave*2,max:type==='brute'?42+wave*3:18+wave*2,speed:type==='brute'?22+wave:39+wave*1.5,hit:0})}}
function start(){reset();state='playing';$('start-screen').classList.remove('active');$('game-over').classList.remove('active');$('pause-screen').classList.remove('active')}
function addParticles(x,y,color,n=6){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=Math.random()*80+20;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.5,color,r:Math.random()*2+1})}}
function shoot(){let a=player.angle;bullets.push({x:player.x+Math.cos(a)*15,y:player.y+Math.sin(a)*15,vx:Math.cos(a)*470,vy:Math.sin(a)*470,r:3,damage:player.damage,life:1.2});player.shoot=0.42/player.rate;addParticles(player.x+Math.cos(a)*14,player.y+Math.sin(a)*14,'#36e5db',2)}
function update(dt){if(state!=='playing')return;elapsed+=dt;player.angle=Math.atan2(mouse.y-player.y,mouse.x-player.x);let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),len=Math.hypot(dx,dy)||1;let speed=180;if(keys[' ']&&player.dash<=0){player.dash=.8;player.inv=.25;speed=540;addParticles(player.x,player.y,'#fa4d9b',12)}if(player.dash>0)player.dash-=dt;if(player.inv>0)player.inv-=dt;player.x=Math.max(20,Math.min(W-20,player.x+dx/len*speed*dt));player.y=Math.max(20,Math.min(H-20,player.y+dy/len*speed*dt));player.shoot-=dt;if(player.shoot<=0)shoot();
 bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});bullets=bullets.filter(b=>b.life>0&&b.x>-20&&b.x<W+20&&b.y>-20&&b.y<H+20);
 enemies.forEach(e=>{let a=Math.atan2(player.y-e.y,player.x-e.x),spd=e.speed*(e.hit>0?.7:1);e.x+=Math.cos(a)*spd*dt;e.y+=Math.sin(a)*spd*dt;e.hit=Math.max(0,e.hit-dt);if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+player.r&&player.inv<=0){if(shield>0)shield=Math.max(0,shield-25*dt);else hp-=22*dt;shake=4}});
 bullets.forEach(b=>enemies.forEach(e=>{if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){b.life=0;e.hp-=b.damage;e.hit=.1;addParticles(b.x,b.y,'#36e5db',3);if(e.hp<=0){e.dead=true;score+=e.type==='brute'?70:25;gainXp(e.type==='brute'?25:10);kills++;addParticles(e.x,e.y,e.type==='brute'?'#fa4d9b':'#36e5db',12)}}}));enemies=enemies.filter(e=>!e.dead);
 if(enemies.length===0){state='upgrade';showUpgrades();}if(hp<=0)die();particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt});particles=particles.filter(p=>p.life>0);shake*=.88;updateHud()}
function gainXp(n){xp+=n;if(xp>=100){xp-=100;level++;player.damage+=2;player.rate+=.08}}
function die(){state='dead';$('final-wave').textContent=String(wave).padStart(2,'0');$('final-score').textContent=String(score).padStart(4,'0');$('game-over').classList.add('active');if(score>best){best=score;localStorage.setItem('voidBest',best)}}
function showUpgrades(){const box=$('upgrade-cards');box.innerHTML='';upgrades.sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let c=document.createElement('div');c.className='upgrade-card';c.innerHTML=`<div class="icon">${u[0]}</div><h3>${u[1]}</h3><p>${u[2]}</p>`;c.onclick=()=>{if(u[1]==='OVERCHARGE')player.damage+=6;if(u[1]==='PHASE SKIN'){player.maxShield+=20;shield=player.maxShield}if(u[1]==='RAPID CORE')player.rate+=.25;if(u[1]==='VOID HEART')hp=Math.min(100,hp+30);wave++;elapsed=0;spawnWave();state='playing';$('upgrade-screen').classList.remove('active');updateHud()};box.appendChild(c)});$('upgrade-screen').classList.add('active')}
function updateHud(){$('wave').textContent=String(wave).padStart(2,'0');$('score').textContent=String(score).padStart(4,'0');$('best').textContent=String(Math.max(best,score)).padStart(4,'0');$('level').textContent=String(level).padStart(2,'0');$('xp-text').textContent=`${Math.floor(xp)} / 100 XP`;$('xp-fill').style.width=xp+'%';$('hp-text').textContent=`${Math.ceil(hp)} / 100`;$('hp-fill').style.width=Math.max(0,hp)+'%';$('shield-text').textContent=`${Math.ceil(shield)} / ${player?.maxShield||40}`;$('shield-fill').style.width=(shield/(player?.maxShield||40)*100)+'%';$('damage-tag').textContent='DMG '+player?.damage;$('rate-tag').textContent='RATE '+(player?.rate||1).toFixed(1)+'×';$('enemy-count').textContent=`${enemies.length} HOSTILES REMAIN`;$('enemy-fill').style.width=(enemies.length/(spawned||1)*100)+'%';$('wave-timer').textContent='00:'+String(Math.max(0,30-Math.floor(elapsed))).padStart(2,'0')}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#080d14';ctx.fillRect(-10,-10,W+20,H+20);let grid=44;ctx.strokeStyle='#12222c';ctx.lineWidth=1;for(let x=0;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#1c3440';ctx.beginPath();ctx.arc(W/2,H/2,Math.min(W,H)*.32,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.25;ctx.strokeStyle='#36e5db';ctx.beginPath();ctx.arc(W/2,H/2,Math.min(W,H)*.5,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;
 particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;bullets.forEach(b=>{ctx.fillStyle='#b7fffb';ctx.shadowBlur=12;ctx.shadowColor='#36e5db';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);let color=e.type==='brute'?'#fa4d9b':'#e05baf';ctx.strokeStyle=color;ctx.shadowBlur=13;ctx.shadowColor=color;ctx.lineWidth=2;ctx.rotate(Math.PI/4);ctx.strokeRect(-e.r*.7,-e.r*.7,e.r*1.4,e.r*1.4);ctx.restore();ctx.fillStyle=color;ctx.beginPath();ctx.arc(e.x,e.y,3,0,Math.PI*2);ctx.fill()});if(player){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.globalAlpha=player.inv>0?.5:1;ctx.strokeStyle='#36e5db';ctx.shadowBlur=20;ctx.shadowColor='#36e5db';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-9,-9);ctx.lineTo(-5,0);ctx.lineTo(-9,9);ctx.closePath();ctx.stroke();ctx.fillStyle='#36e5db';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore();requestAnimationFrame(draw)}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);requestAnimationFrame(loop)}
window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Escape'&&state==='playing'){state='paused';$('pause-screen').classList.add('active')}else if(e.key==='Escape'&&state==='paused'){state='playing';$('pause-screen').classList.remove('active')}if(e.key===' '){e.preventDefault()}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top});canvas.addEventListener('touchmove',e=>{let r=canvas.getBoundingClientRect(),t=e.touches[0];mouse.x=t.clientX-r.left;mouse.y=t.clientY-r.top},{passive:true});$('start-btn').onclick=start;$('restart-btn').onclick=start;resize();requestAnimationFrame(draw);requestAnimationFrame(loop);
